config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, only: [:show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, :dependent => :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, presence: true, uniqueness: {scope: :ingredient}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end
  def new
    @cocktail = Cocktail.new
  end
  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end
  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end
  private
  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController     
      def new
        @dose = Dose.new
        @cocktail = Cocktail.find(params[:cocktail_id])
      end
    
      def create
        @dose = Dose.new(dose_params)
        @cocktail = Cocktail.find(params[:cocktail_id])
        @dose.cocktail = @cocktail
        if @dose.save
          redirect_to cocktail_path(@cocktail)
        else
          render "cocktails/show"
        end
      end
    
      def destroy
        dose = Dose.find(params[:id])
        dose.destroy
        redirect_to cocktail_path(dose.cocktail)
      end
      

      private
    
      def dose_params
        params.require(:dose).permit(:ingredient_id, :description)
      end
    end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
    def index
        @ingredients = Ingredient.all
      end
    
      def show
        @ingredient = Ingredient.find(params[:id])
      end
    
      def new
        @ingredient = Ingredient.new
      end
    
      def create
        @ingredient = Ingredient.new(ingredient_params)
        if @ingredient.save
          redirect_to ingredient_path(@ingredient)
        else
          render "new"
        end
      end
    
      private
    
      def ingredient_params
        params.require(:ingredient).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>All cocktails</h1>
      <%= link_to "Add a cocktail", new_cocktail_path, class: "btn btn-red" %>
      <ul class="list-group">
        <% @cocktails.each do |cocktail| %>
          <li class="list-group-item">
          <%= link_to cocktail.name, cocktail_path(cocktail) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>Create a new cocktail</h1>
      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1><%= @cocktail.name %></h1>
      <ul>
      <% @cocktail.doses.each do |dose| %>
        <li><%= dose.description %>
        <%= dose.ingredient.name %>
        <%= link_to "Delete dose",
                      dose_path(dose),
                      method: :delete,
                      data: { confirm: "Are you sure?" } %></li>
      <% end %>
      </ul>
      <%= link_to 'back', root_path(@cocktail), class: "btn btn-primary" %>
    </div>
  </div>
</div>

<%= render 'doses/new' %>

app/views/doses/_new.html.erb
<div class="container form-container">
<h2 class="text-center">Add a new dose</h2>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <div class="input-group mb-3">
      <%= f.label :description %>
      <%= f.text_field :description, placeholder: "3cl" %>
    </div>
    <div class="input-group mb-3">
      <%= f.association :ingredient, label: false, prompt: "Choose ingredient" %>
    </div>
      <%= f.submit 'Add!' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>